In [41]:
import numpy as np

arr = np.arange(0,20,1)
arr = np.reshape(arr, (5,4))
arr[0,0] = 100
print(arr)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]
 [ 16  17  18  19]]


In [42]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(5, 4)
20
int32


In [43]:
print(arr[0,0])
print(arr[2,2])
print(arr[4,3])
print(arr[:,2])
print(arr[2,:])
print(arr[:2,:3])
print(arr[:,:3])

100
10
19
[ 2  6 10 14 18]
[ 8  9 10 11]
[[100   1   2]
 [  4   5   6]]
[[100   1   2]
 [  4   5   6]
 [  8   9  10]
 [ 12  13  14]
 [ 16  17  18]]


In [44]:
sum_arr = np.sum(arr)
print(sum_arr)
medium = np.mean(arr)
print(medium)
median = np.median(arr)
print(median)

290
14.5
10.5


In [57]:
stand = np.std(arr)
print(stand)
mini = np.min(arr)
print(mini)
maxi = np.max(arr)
print(maxi)
argMin = np.argmin(arr, 0)
print(argMin)
argMax = np.argmax(arr, 1)
print(argMax)
print(np.cumsum(arr))
print(np.cumprod(arr))

20.328551350256124
1
100
[1 0 0 0]
[0 3 3 3 3]
[100 101 103 106 110 115 121 128 136 145 155 166 178 191 205 220 236 253
 271 290]
[        100         100         200         600        2400       12000
       72000      504000     4032000    36288000   362880000  -303287296
   655519744   -68177920  -954490880 -1432461312 -1444544512  1212547072
   351010816 -1920729088]
